const { app, BrowserWindow, BrowserView, session, ipcMain, shell, Menu } = require('electron');
const path = require('path');
const fs = require('fs');
const START_URL = process.env.CHROME_PRO_START_URL || 'https://www.google.com';
const SEARCH_URL = process.env.CHROME_PRO_SEARCH_URL || 'https://www.google.com/search?q=';
const UI_HEIGHT = 94, NAV_TIMEOUT_MS = 20000, windows = new Map(); let activeWindow = null;
const dataFile=()=>path.join(app.getPath('userData'),'browser-data.json');
let data={bookmarks:[],bookmarkFolders:[{id:'root',name:'Favorites'}],history:[]};
function loadData(){try{data={...data,...JSON.parse(fs.readFileSync(dataFile(),'utf8'))}}catch(_){} if(!Array.isArray(data.bookmarks))data.bookmarks=[];if(!Array.isArray(data.bookmarkFolders)||!data.bookmarkFolders.length)data.bookmarkFolders=[{id:'root',name:'Favorites'}];data.bookmarks=data.bookmarks.map(x=>({...x,folderId:x.folderId||'root'}))}
function saveData(){try{fs.mkdirSync(path.dirname(dataFile()),{recursive:true});fs.writeFileSync(dataFile(),JSON.stringify(data,null,2))}catch(e){console.error(e)}}
const profilePath=n=>path.join(app.getPath('userData'),'profiles',n);
function normalizeUrl(input){const v=String(input||'').trim();if(!v)return START_URL;try{return new URL(v).href}catch(_){}if(/^[\w.-]+\.[a-z]{2,}(\/.*)?$/i.test(v))return `https://${v}`;return `${SEARCH_URL}${encodeURIComponent(v)}`}
function alive(v){return !!(v&&v.webContents&&!v.webContents.isDestroyed())} function canGoBack(t){return alive(t)&&t.webContents.navigationHistory.canGoBack()} function canGoForward(t){return alive(t)&&t.webContents.navigationHistory.canGoForward()}
function layout(w,s){const b=w.getContentBounds(),h=Math.max(1,b.height-UI_HEIGHT);for(const v of s.tabs)if(alive(v))v.setBounds({x:0,y:UI_HEIGHT,width:b.width,height:h});const a=s.tabs[s.active];if(alive(a))w.setTopBrowserView(a)}
function stateTabs(s){return s.tabs.map(v=>({title:alive(v)?v.webContents.getTitle()||'New Tab':'New Tab',url:alive(v)?v.webContents.getURL():'',loading:alive(v)&&v.webContents.isLoading(),canGoBack:canGoBack(v),canGoForward:canGoForward(v)}))}
function sendState(s){if(alive(s.chrome))s.chrome.webContents.send('browser:state',{active:s.active,profile:s.profile,incognito:s.incognito,tabs:stateTabs(s)})}
function navigationErrorPage(code,description,url){const html=`<!doctype html><html><body style="margin:0;background:#f8f9fa;color:#202124;font:16px system-ui;display:grid;place-items:center;height:100vh"><main style="max-width:620px;padding:40px;text-align:center"><h1>We couldn't load this page</h1><p>Check your internet connection or try again.</p><code>${String(code||'NETWORK_ERROR')} — ${String(description||'Connection failed')}</code><p style="word-break:break-all">${String(url||'')}</p><button onclick="history.back()">Go back</button></main></body></html>`;return`data:text/html;charset=utf-8,${encodeURIComponent(html)}`}
function createWindow(profile='default',incognito=false){const ses=incognito?session.fromPartition(`incognito-${Date.now()}-${Math.random()}`):session.fromPath(profilePath(profile),{cache:true});const win=new BrowserWindow({width:1440,height:900,minWidth:1000,minHeight:650,title:incognito?'Chrome Pro — Incognito':'Chrome Pro',backgroundColor:'#111317',frame:true,resizable:true,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,sandbox:false,nodeIntegration:false}});const s={profile,incognito,session:ses,tabs:[],active:0,chrome:null};windows.set(win.id,s);activeWindow=win;
const addTab=(u=START_URL)=>{const v=new BrowserView({webPreferences:{session:ses,contextIsolation:true,sandbox:true,nodeIntegration:false}});s.tabs.push(v);s.active=s.tabs.length-1;win.addBrowserView(v);layout(win,s);v.webContents.loadURL(normalizeUrl(u),{timeout:NAV_TIMEOUT_MS}).catch(e=>console.warn('Navigation failed:',e.code||e.message));v.webContents.on('did-navigate',(_e,n)=>{if(!incognito){data.history.unshift({url:n,title:v.webContents.getTitle()||n,time:Date.now()});data.history=data.history.slice(0,500);saveData()}sendState(s)});['did-start-loading','did-stop-loading','page-title-updated','did-fail-load','did-navigate-in-page'].forEach(e=>v.webContents.on(e,()=>sendState(s)));v.webContents.on('did-fail-load',(_e,c,d,f,main)=>{if(main&&c!==-3)v.webContents.loadURL(navigationErrorPage(c,d,f)).catch(()=>{})});v.webContents.on('render-process-gone',()=>sendState(s));sendState(s);return v};
s.addTab=addTab;s.chrome=win.webContents;win.loadFile(path.join(__dirname,'browser-ui.html'));win.webContents.once('did-finish-load',()=>{layout(win,s);sendState(s)});addTab();win.on('resize',()=>layout(win,s));win.on('focus',()=>{activeWindow=win;layout(win,s);sendState(s)});win.on('closed',()=>{s.tabs.forEach(v=>{if(alive(v))v.webContents.destroy()});windows.delete(win.id);if(activeWindow===win)activeWindow=BrowserWindow.getAllWindows()[0]||null});return win}
function state(){return windows.get(activeWindow?.id)} function activeTab(){const s=state();return s?.tabs[s.active]}
app.whenReady().then(()=>{loadData();const handlers={
'app:info':()=>({name:'Chrome Pro',version:app.getVersion(),platform:process.platform,arch:process.arch}),'window:minimize':()=>activeWindow?.minimize(),'window:maximize':()=>{if(!activeWindow)return false;activeWindow.isMaximized()?activeWindow.unmaximize():activeWindow.maximize();return activeWindow.isMaximized()},'window:close':()=>activeWindow?.close(),
'browser:open':(_e,u)=>state()?.addTab(u),'browser:new-tab':()=>state()?.addTab(),'browser:close-tab':(_e,i)=>{const s=state();if(!s||!s.tabs.length)return false;const n=Number.isInteger(i)?i:s.active;if(n<0||n>=s.tabs.length)return false;const v=s.tabs[n];if(alive(v))activeWindow.removeBrowserView(v);if(alive(v))v.webContents.destroy();s.tabs.splice(n,1);if(!s.tabs.length)s.addTab();else{s.active=Math.min(n,s.tabs.length-1);layout(activeWindow,s);sendState(s)}return true},
'browser:switch-tab':(_e,i)=>{const s=state(),n=Number(i);if(!s||!Number.isInteger(n)||n<0||n>=s.tabs.length||!alive(s.tabs[n]))return false;s.active=n;layout(activeWindow,s);sendState(s);return true},'browser:navigate':async(_e,u)=>{const t=activeTab();if(!t)return false;try{await t.webContents.loadURL(normalizeUrl(u),{timeout:NAV_TIMEOUT_MS});return true}catch(e){return false}},'browser:back':()=>{const t=activeTab();return t&&canGoBack(t)?t.webContents.navigationHistory.goBack():false},'browser:forward':()=>{const t=activeTab();return t&&canGoForward(t)?t.webContents.navigationHistory.goForward():false},'browser:reload':()=>activeTab()?.webContents.reload(),'browser:stop':()=>{const t=activeTab();if(!t||!t.webContents.isLoading())return false;t.webContents.stop();sendState(state());return true},'browser:new-profile':(_e,n)=>createWindow(String(n||'profile').replace(/[^a-z0-9_-]/gi,'_')).id,'browser:incognito':()=>createWindow('incognito',true).id,'browser:tabs':()=>{const s=state();return s?{active:s.active,profile:s.profile,incognito:s.incognito,tabs:stateTabs(s)}:{active:0,tabs:[]}},
'browser:history':()=>data.history,'browser:delete-history':(_e,index)=>{const i=Number(index);if(i>=0&&i<data.history.length)data.history.splice(i,1);saveData();return data.history},'browser:clear-history':()=>{data.history=[];saveData();return true},
'browser:bookmarks':()=>data.bookmarks,'browser:bookmark-folders':()=>data.bookmarkFolders,'browser:add-bookmark':(_e,b)=>{if(!b?.url)return data.bookmarks;const existing=data.bookmarks.find(x=>x.url===b.url);if(existing){existing.title=String(b.title||existing.title||b.url);existing.folderId=String(b.folderId||existing.folderId||'root')}else data.bookmarks.unshift({title:String(b.title||b.url),url:String(b.url),time:Date.now(),folderId:String(b.folderId||'root')});saveData();return data.bookmarks},'browser:remove-bookmark':(_e,u)=>{data.bookmarks=data.bookmarks.filter(x=>x.url!==u);saveData();return data.bookmarks},'browser:create-folder':(_e,name)=>{const n=String(name||'').trim();if(!n)return data.bookmarkFolders;data.bookmarkFolders.push({id:`folder-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:n});saveData();return data.bookmarkFolders},'browser:rename-folder':(_e,id,name)=>{const f=data.bookmarkFolders.find(x=>x.id===id);if(f&&id!=='root'&&String(name||'').trim())f.name=String(name).trim();saveData();return data.bookmarkFolders},'browser:delete-folder':(_e,id)=>{if(id==='root')return data.bookmarkFolders;data.bookmarks=data.bookmarks.map(x=>x.folderId===id?{...x,folderId:'root'}:x);data.bookmarkFolders=data.bookmarkFolders.filter(x=>x.id!==id);saveData();return data.bookmarkFolders},'browser:move-bookmark':(_e,url,folderId)=>{const b=data.bookmarks.find(x=>x.url===url);if(b&&data.bookmarkFolders.some(f=>f.id===folderId))b.folderId=folderId;saveData();return data.bookmarks},
'browser:downloads':()=>app.getPath('downloads'),'browser:clear-data':async()=>{const s=state();if(s&&!s.incognito){await s.session.clearCache();await s.session.clearStorageData()}return true},'browser:external':async(_e,u)=>{if(typeof u==='string'&&/^https?:/i.test(u))await shell.openExternal(u);return true}};Object.entries(handlers).forEach(([k,fn])=>ipcMain.handle(k,fn));
Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'Browser',submenu:[{label:'New Tab',accelerator:'CmdOrCtrl+T',click:()=>state()?.addTab()},{label:'New Incognito Window',accelerator:'CmdOrCtrl+Shift+N',click:()=>createWindow('incognito',true)},{label:'New Profile',accelerator:'CmdOrCtrl+Shift+P',click:()=>createWindow(`profile-${Date.now()}`)},{type:'separator'},{role:'reload'},{role:'toggledevtools'},{role:'quit'}]}]));session.defaultSession.setPermissionRequestHandler((_wc,p,cb)=>cb(['notifications','fullscreen','media'].includes(p)));createWindow();app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})}).catch(e=>{console.error('Chrome Pro startup failed:',e);app.quit()});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});